// ISI DATA KONTAK KAMU DI SINI. Ikon di bagian kontak akan otomatis memakai tautan ini.
const profile = {
  instagram: 'https://www.instagram.com/ptriinurfzh16_?igsh=MTNnNHBwZzBicWk4Yg==',
  github: 'https://github.com/fithrinurfaizah-spec',
  // Ganti angka setelah wa.me dengan nomor WhatsApp kamu, tanpa 0, +, atau spasi.
  whatsapp: 'https://wa.me/6285713418493',
  email: 'fithrinf10@gmail.com'
};
document.querySelector('#instagram-link').href = profile.instagram;
document.querySelector('#github-link').href = profile.github;
document.querySelector('#whatsapp-link').href = profile.whatsapp;
document.querySelector('#email-link').href = `mailto:${profile.email}`;

// ISI PROYEK KAMU DI SINI.
// Duplikat satu blok { ... } di bawah, lalu isi judul, gambar, deskripsi,
// teknologi, status, fitur, tantangan, solusi, demo, dan github.
const projects = [
  {id:'kasir',title:'Kasir Digital',category:['website','javascript','sekolah'],image:'assets/images/kasir-digital.png',desc:'Aplikasi kasir sederhana untuk pencatatan transaksi toko buah.',tech:['HTML','Bootstrap','JavaScript'],status:'Selesai',features:['Manajemen produk dan stok','Perhitungan total otomatis','Riwayat transaksi'],challenge:'Menjaga data transaksi tetap konsisten saat pengguna mengubah jumlah produk.',solution:'Membuat fungsi validasi stok dan pembaruan total secara real-time.',demo:'#',github:'https://github.com/username_kamu/nama-repository'},
  {id:'seblak',title:'Seblak Ngapak',category:['uiux','website'],image:'assets/images/seblak-ngapak-full.png',fit:'contain',desc:'Desain aplikasi pemesanan Seblak Ngapak dengan tampilan hangat dan mudah digunakan.',tech:['Figma','HTML','CSS'],status:'Selesai',features:['Kategori menu','Keranjang belanja','Daftar menu populer'],challenge:'Menampilkan pilihan menu agar tetap jelas di layar ponsel.',solution:'Menerapkan kartu menu yang ringkas dan navigasi bawah yang mudah dijangkau.',demo:'#',github:'https://github.com/username_kamu/nama-repository'},
  {id:'grillmate',title:'GrillMate',category:['website','uiux','sekolah'],image:'assets/images/grillmate-desktop.png',fit:'contain',desc:'Website reservasi restoran grill dan BBQ untuk memilih meja, area, serta paket menu.',tech:['HTML','Bootstrap','PHP'],status:'Selesai',features:['Booking meja','Pilihan area makan','Daftar paket grill'],challenge:'Menyusun informasi reservasi agar nyaman dipakai dari ponsel.',solution:'Menerapkan navigasi sederhana, informasi ringkas, dan tombol aksi yang jelas.',demo:'#',github:'https://github.com/username_kamu/nama-repository'}
];
const grid=document.querySelector('#project-grid');
function renderProjects(filter='all'){grid.innerHTML=projects.map(p=>`<article class="project-card glass reveal visible ${filter==='all'||p.category.includes(filter)?'':'hidden'}"><div class="project-image ${p.fit||''}"><img src="${p.image}" alt="Preview proyek ${p.title}"><span class="project-status">${p.status}</span></div><div class="project-body"><div class="project-meta"><span>${p.category[0]}</span><span>2026</span></div><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tech.map(t=>`<span>${t}</span>`).join('')}</div><div class="project-links"><button data-detail="${p.id}">Lihat Detail <i class="fa-solid fa-arrow-right"></i></button>${p.demo==='#'?`<a href="#" data-demo="${p.title}">Demo</a>`:`<a href="${p.demo}" target="_blank" rel="noopener">Demo</a>`}<a href="${p.github}" target="_blank" rel="noopener">GitHub <i class="fa-solid fa-arrow-up-right-from-square"></i></a></div></div></article>`).join('')}
renderProjects();
const modal=document.querySelector('#project-modal'),modalContent=document.querySelector('#modal-content');
function openProject(id){const p=projects.find(x=>x.id===id);modalContent.innerHTML=`<img class="modal-hero ${p.fit||''}" src="${p.image}" alt="${p.title}"><p class="eyebrow">${p.category.join(' · ')}</p><h2>${p.title}</h2><p>${p.desc} Proyek ini dibuat untuk memperdalam proses membangun produk digital dari ide hingga antarmuka siap pakai.</p><h3>Fitur utama</h3><ul>${p.features.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Teknologi</h3><div class="tags">${p.tech.map(x=>`<span>${x}</span>`).join('')}</div><h3>Tantangan & solusi</h3><p><b>Tantangan:</b> ${p.challenge}<br><b>Solusi:</b> ${p.solution}</p><div class="modal-gallery">${[p.image,'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=500&q=70','https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=500&q=70'].map(x=>`<img src="${x}" alt="Galeri ${p.title}">`).join('')}</div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
document.addEventListener('click',e=>{const detail=e.target.closest('[data-detail]');if(detail)openProject(detail.dataset.detail);const demo=e.target.closest('[data-demo]');if(demo){e.preventDefault();showToast(`Demo ${demo.dataset.demo} akan segera tersedia.`)}});
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelector('.modal-close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelectorAll('.filters button').forEach(btn=>btn.onclick=()=>{document.querySelector('.filters .selected').classList.remove('selected');btn.classList.add('selected');renderProjects(btn.dataset.filter)});
const toggle=document.querySelector('.theme-toggle');function setTheme(dark){document.body.classList.toggle('dark',dark);toggle.innerHTML=`<i class="fa-solid fa-${dark?'sun':'moon'}"></i>`;localStorage.setItem('fithri-theme',dark?'dark':'light')}setTheme(localStorage.getItem('fithri-theme')==='dark');toggle.onclick=()=>setTheme(!document.body.classList.contains('dark'));
const hamburger=document.querySelector('.hamburger'),menu=document.querySelector('#nav-menu');hamburger.onclick=()=>{const open=menu.classList.toggle('open');hamburger.setAttribute('aria-expanded',open);hamburger.innerHTML=`<i class="fa-solid fa-${open?'xmark':'bars'}"></i>`};menu.querySelectorAll('a').forEach(a=>a.onclick=()=>{menu.classList.remove('open');hamburger.setAttribute('aria-expanded','false');hamburger.innerHTML='<i class="fa-solid fa-bars"></i>'});
const sections=document.querySelectorAll('main section'),links=document.querySelectorAll('nav a');const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.classList.contains('skill-card')){e.target.classList.add('animate');const number=e.target.querySelector('[data-percent]');const end=+number.dataset.percent;let n=0;const t=setInterval(()=>{number.textContent=`${n}%`;if(n>=end)clearInterval(t);n++},12)}}}),{threshold:.16});document.querySelectorAll('.reveal').forEach(x=>revealObserver.observe(x));
const spy=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>spy.observe(s));
const navbar=document.querySelector('#navbar'),back=document.querySelector('.back-top');window.addEventListener('scroll',()=>{navbar.classList.toggle('scrolled',scrollY>20);back.classList.toggle('show',scrollY>300)});back.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
const typing=document.querySelector('#typing'),words=['Front-End Developer.','UI/UX Enthusiast.','Siswa RPL.'];let wi=0,ci=0,deleting=false;function type(){const word=words[wi];typing.textContent=word.slice(0,ci);if(!deleting&&ci++===word.length){deleting=true;setTimeout(type,1400);return}if(deleting&&ci--===0){deleting=false;wi=(wi+1)%words.length}setTimeout(type,deleting?45:85)}type();
const form=document.querySelector('#contact-form');function showToast(message){const toast=document.querySelector('.toast');toast.querySelector('span').textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3500)}form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form)),error=form.querySelector('.form-error');if(Object.values(data).some(v=>!v.trim())){error.textContent='Mohon isi semua kolom terlebih dahulu.';return}if(!/^\S+@\S+\.\S+$/.test(data.email)){error.textContent='Masukkan alamat email yang valid.';return}error.textContent='';const btn=form.querySelector('button');const original=btn.innerHTML;btn.classList.add('loading');btn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Mengirim...';try{const response=await fetch(`https://formsubmit.co/ajax/${profile.email}`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...data,_subject:'Pesan baru dari website portofolio Fithri',_template:'table'})});if(!response.ok)throw new Error('Gagal mengirim');form.reset();showToast('Pesan terkirim! Terima kasih sudah menghubungi.')}catch{error.textContent='Pesan belum terkirim. Coba lagi beberapa saat.'}finally{btn.classList.remove('loading');btn.innerHTML=original}};
document.querySelector('#download-cv').onclick=e=>{e.preventDefault();const lines=['Fithri Nur Faizah - Curriculum Vitae','Siswa Rekayasa Perangkat Lunak',`Email: ${profile.email}`,'Keahlian: HTML5, CSS3, JavaScript, UI/UX Design'];const stream=['BT','/F1 18 Tf','72 740 Td',`(${lines[0]}) Tj`,'0 -32 Td','/F1 12 Tf',...lines.slice(1).flatMap(line=>[`(${line}) Tj`,'0 -22 Td']),'ET'].join('\n');const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((obj,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const url=URL.createObjectURL(new Blob([pdf],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download='Fithri-Nur-Faizah-CV.pdf';a.click();URL.revokeObjectURL(url)};
window.addEventListener('load',()=>setTimeout(()=>document.querySelector('.loader').classList.add('hide'),450));
